FORMAT: 1A
HOST: http://containers-api.compology.com/v2/


# Compology Containers API

**VERSION 2 (v2) FOR RELEASE**

The Compology API allows you to query data about your containers.

The API is based on REST principles, making it conform to industry-standard
approaches, and making it easy to implement and test clients. You can use
**curl** to test URLs and you can use any programming language to interact
with the API.

Use cases of this API include (but are not limited to):

 * Getting a list of containers
 * Getting a list of containers for a specific customer
 * Getting a list of device posts for a specific container

## Using Apiary.io interactive docs

This document is hosted on Apiary.io. To see endpoints and example responses,
click on the "200 OK" buttons. This will open a panel showing more details.

The button labeled "Try console" is not supported at this time.

## Authentication
API access will be supported only via HTTPS.

Users of this API will receive a JWT token. When a client makes a request to
the API, this token shall be included in the `Authorization` header.

The header shall be formatted thusly: `Bearer <your token>`.

## Rate limiting
Compology's current rate limiting policy is `50` requests every `30` seconds.
A higher frequency of requests will result in rate limiting.

All requests return headers similar to these:
```
'retry-after': '300', 
'x-ratelimit-limit': '50',
'x-ratelimit-remaining': '0',
'x-ratelimit-reset': 'Mon, 02 Dec 2019 23:50:07 GMT'
```

If your application requires higher limits than these, please contact support.

## Error handling

### 200s
Successes will be HTTP responses with status codes between 200-299.

### 400s
Client errors will be indicated by HTTP responses with status codes
between 400-499.

This level of error will be accompanied by an HTTP body containing JSON
data with descriptive information about the error.

### 500s
Server-side or network errors will be indicated by HTTP responses with
status codes between 500-599.

## Standard Responses

Non-error responses from this API will be a single JSON object. Top-level
keys of this object are standardized:

```json
{
  "payload": ...
  "prev": ...
  "next": ...
  "client": [
    ...
  ]
}
```

 * "payload" - The main body of the response and usually what the API
   client is most interested in.
 * "prev" - *optional* -  A link to the previous page in the collection.
 * "next" - *optional* - A link to the next page in the collection.
 * "client" - This contains advised or required HTTP headers and other
   information that the client may wish to include in requests.

If the HTTP REST resource is a single resource, "next" and "prev" keys will
be absent.  If the resource is a collection, "next" and "prev" keys *may*
be present.

Note, different endpoints have different rules about how they provide
"next" and "prev" keys. Some endpoints indicate that the current payload
is the end of a collection by returning a response that has no "next" key.
Other endpoints always respond with a "next" key and indicate the end of
a collection by returning an empty array as the payload value.
It is up to the client to determine the boundaries of the collection.
The mere existence of a "next" or "prev" link is not always sufficient to
decide this.

A generally applicable algorithm to visit all the pages in a collection is to
start at the first page and iterate forward until the API responds with either
no "next" link or an empty payload.


## Login [/login]

The `/login` endpoint can be used to get a new authorization token.
You may choose to get your token via this API method, or via the
web app.

### Your Authorization Token [GET]

#### example

```bash
export BASE=https://containers-api.compology.com/v2
curl -H "Content-Type: application/json" ${BASE}/login --data '{"email":"...","password":"..."}'
```

+ Response 200 (application/json)

    + Body

            {
            "payload": {
              "token": "eyJ00000000IUzI1NiIkpXVCJ9.eyJv00000000InJlYWxwYWdlIiwidXNlcklkI0000000DF9.0mx00000000q_Xw6woMj8Z-LILT4wu1vfQHTtTgcMUo"
            },
            "client": [
              "X-Compology-Version: 2019-07-25/1",
              "Authorization: Bearer eyJ00000000IUzI1NiIkpXVCJ9.eyJv00000000InJlYWxwYWdlIiwidXNlcklkI0000000DF9.0mx00000000q_Xw6woMj8Z-LILT4wu1vfQHTtTgcMUo"
            ]
            }

## Containers [/containers]

### List All Containers [GET]

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/containers
```

+ Parameters
 + cursor: (string, optional)

+ Response 200 (application/json)

    + Body

            {
            "payload": [
               {
                "id": "1234NDROPWASTE_00022",
                "containerType": "roll off",
                "contentType": "refuse",
                "cubicYards": 20,
                "description": "20-0013",
                "externalId": "7J2TT262M2PX",
                "hasAccuratePosition": true,
                "lastClassifiedCameraBlocked": false,
                "lastGpsIsAccurate": true,
                "lastImageTimestamp": "2018-10-15T20:06:19.780Z",
                "lastImageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-c7c82e7fc79e",
                "level": 0,
                "location": {},
                "locationUpdatedAt": "2018-08-11T06:03:51.922Z",
                "latitude": 37.771789,
                "longitude": -122.407272,
                "maybeLastEmptiedAt": "2018-06-12T19:58:11.000Z",
                "pendingClassification": true,
                "pickupSchedule": {
                    "currency": "usd",
                    "frequency": "weekly",
                    "friday": false,
                    "monday": true,
                    "price": "120.00",
                    "saturday": false,
                    "sunday": false,
                    "thursday": true,
                    "tuesday": false,
                    "wednesday": false
                },
                "positionAccuracy": 15,
                "technicianAssigned": true,
                "updatedAt": "2019-07-23T23:54:26.057Z"
              },
              {
                "id": "1234NDROPWASTE_00023",
                "containerType": "roll off",
                "contentType": "refuse",
                "cubicYards": 20,
                "description": "20-0014",
                "externalId": "NDHSYG067HN4",
                "hasAccuratePosition": true,
                "lastClassifiedCameraBlocked": true,
                "lastGpsIsAccurate": true,
                "lastImageTimestamp": "2019-07-26T20:39:56.922Z",
                "lastImageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-0ed886d837f1",
                "level": 100,
                "location": {
                  "id": "12341111-1111-1111-1111-789838c8d804",
                  "externalId": null,
                  "description": "Travis County Landfill",
                  "street": "9600 812 Rd",
                  "city": "Austin",
                  "state": "Texas",
                  "postalCode": "78719",
                  "zip": "78719"
                },
                "locationUpdatedAt": "2019-07-25T22:39:55.392Z",
                "latitude": 30.210447,
                "longitude": -97.850021,
                "maybeLastEmptiedAt": "2018-06-27T21:02:13.000Z",
                "pendingClassification": false,
                "pickupSchedule": {
                    "currency": null,
                    "frequency": null,
                    "friday": null,
                    "monday": null,
                    "price": null,
                    "saturday": null,
                    "sunday": null,
                    "thursday": null,
                    "tuesday": null,
                    "wednesday": null
                },
                "positionAccuracy": 30,
                "technicianAssigned": false,
                "updatedAt": "2019-07-26T20:41:33.851Z"
              }
            ],
            "client": [
              "X-Compology-Version: 2019-07-25/1"
            ],
            "next": "https://containers-api.compology.com/v2/containers/?cursor=eyJkaXJlY3Rpb240YWIwNGZmIn0%3D"
            }

## Device Posts for a Container [/containers/{containerId}/device_posts]

### List All Device Posts [GET]

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/containers/<container id>/device_posts
```

+ Parameters
 + cursor: (string, optional)

+ Response 200 (application/json)

    + Body

            {
              "payload": [
                {
                  "id": "12341111-1111-1111-1111-04bcbcdeabba",
                  "organizationId": "dragndropwaste",
                  "container": {
                    "id": "1234NDROPWASTE_00014",
                    "contentType": "refuse",
                    "cubicYards": 20,
                    "description": "20-0009",
                    "externalId": "YRTRPS4HCB91"
                  },
                  "customer": {
                    "id": "12341111-1111-1111-1111-adcf55452f6c",
                    "externalId": "abc123",
                    "name": "Alicia Marie Fricazee"
                  },
                  "location": {
                    "id": "12341111-1111-1111-1111-75f12747b600",
                    "externalId": null,
                    "description": "Zellers"
                  },
                  "occurredAt": "2019-07-26T22:19:07.799Z",
                  "level": null,
                  "maybeWasEmptied": null,
                  "maybeEmptyOccurredAt": null,
                  "latitude": 30.312946,
                  "longitude": -97.986297,
                  "latLonRadius": 9.3,
                  "cameraBlocked": null,
                  "imageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-04bcbcdeabba"
                },
                {
                  "id": "12341111-1111-1111-1111-c0fcbb27485c",
                  "organizationId": "dragndropwaste",
                  "container": {
                    "id": "1234NDROPWASTE_00014",
                    "contentType": "refuse",
                    "cubicYards": 20,
                    "description": "20-0009",
                    "externalId": "YRTRPS4HCB91"
                  },
                  "customer": {
                    "id": "12341111-1111-1111-1111-adcf55452f6c",
                    "externalId": "abc123",
                    "name": "Alicia Marie Fricazee"
                  },
                  "location": {
                    "id": "12341111-1111-1111-1111-75f12747b600",
                    "externalId": null,
                    "description": "Zellers"
                  },
                  "occurredAt": "2019-07-26T18:07:58.364Z",
                  "level": null,
                  "maybeWasEmptied": null,
                  "maybeEmptyOccurredAt": null,
                  "latitude": 30.312938,
                  "longitude": -97.986305,
                  "latLonRadius": 25,
                  "cameraBlocked": null,
                  "imageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-c0fcbb27485c"
                },
                {
                  "id": "12341111-1111-1111-1111-b159f4ab04ff",
                  "organizationId": "dragndropwaste",
                  "container": {
                    "id": "1234NDROPWASTE_00014",
                    "contentType": "refuse",
                    "cubicYards": 20,
                    "description": "20-0009",
                    "externalId": "YRTRPS4HCB91"
                  },
                  "customer": {
                    "id": null,
                    "externalId": null,
                    "name": null
                  },
                  "location": {
                    "id": null,
                    "externalId": null,
                    "description": null
                  },
                  "occurredAt": "2019-06-28T04:24:40.831Z",
                  "level": 35,
                  "maybeWasEmptied": false,
                  "maybeEmptyOccurredAt": null,
                  "latitude": 30.48846,
                  "longitude": -98.201461,
                  "latLonRadius": 6.5,
                  "cameraBlocked": false,
                  "imageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-b159f4ab04ff"
                }
              ],
              "client": [
                "X-Compology-Version: 2019-07-25/1"
              ],
              "prev": "https://containers-api.compology.com/v2/containers/DRAGNDROPWASTE_00014/device_posts?cursor=eyJka0YmNiY2RlYWJiYSJ9",
              "next": "https://containers-api.compology.com/v2/containers/DRAGNDROPWASTE_00014/device_posts?cursor=eyJkaY0YWIwNGZmIn0%3D"
            }


## Device Post by ID [/containers/{containerId}/device_posts/{devicePostId}]

### Get Device Post [GET]

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/containers/<container id>/device_posts/<device post id>
```

+ Response 200 (application/json)

    + Body

            {
              "payload": {
                "id": "123471d5-b189-4b6e-aeb4-53e7958e5fc0",
                "organizationId": "dragndropwaste",
                "container": {
                  "id": "1234NDROPWASTE_00014",
                  "contentType": "refuse",
                  "cubicYards": 20,
                  "description": "20-0009",
                  "externalId": "YRTRPS4HCB91"
                },  
                "customer": {
                  "id": "12341525-206e-447a-940c-adcf55452f6c",
                  "externalId": "abc123",
                  "name": "Alicia Marie Fricazee"
                },  
                "location": {
                  "id": "1234aac9-c884-4f60-8559-75f12747b600",
                  "externalId": null,
                  "description": "Zellers"
                },  
                "occurredAt": "2019-06-27T19:59:36.534Z",
                "level": 30,
                "maybeWasEmptied": false,
                "maybeEmptyOccurredAt": null,
                "latitude": 30.488445,
                "longitude": -98.201553,
                "latLonRadius": 24,
                "cameraBlocked": false,
                "imageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-53e7958e5fc0"
              },  
              "client": [
                "X-Compology-Version: 2019-07-25/1"
              ]
            }

## Device Post by Timestamp [/containers/{containerId}/device_posts/occurred_at/{timestamp}]

### Get Device Post [GET]

This will return the Device Post for the specified Container that occurred at
the specified time.  If no Device Post occurred at *exactly* the specified time,
it will return the **latest** Device Post that occurred **before** the specified
time.

The `timestamp` must be specified in a valid ISO-8601 format.

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/containers/<container id>/device_posts/occurred_at/<timestamp>
```

+ Response 200 (application/json)

    + Body

            {
              "payload": {
                "id": "12341111-1111-1111-1111-53e7958e5fc0",
                "organizationId": "dragndropwaste",
                "container": {
                  "id": "1234NDROPWASTE_00014",
                  "contentType": "refuse",
                  "cubicYards": 20,
                  "description": "20-0009",
                  "externalId": "YRTRPS4HCB91"
                },  
                "customer": {
                  "id": "12341111-1111-1111-1111-adcf55452f6c",
                  "externalId": "abc123",
                  "name": "Alicia Marie Fricazee"
                },  
                "location": {
                  "id": "12341111-1111-1111-1111-75f12747b600",
                  "externalId": null,
                  "description": "Zellers"
                },  
                "occurredAt": "2019-06-27T19:59:36.534Z",
                "level": 30,
                "maybeWasEmptied": false,
                "maybeEmptyOccurredAt": null,
                "latitude": 30.488445,
                "longitude": -98.201553,
                "latLonRadius": 24,
                "cameraBlocked": false,
                "imageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-53e7958e5fc0"
              },  
              "client": [
                "X-Compology-Version: 2019-07-25/1"
              ]
            }

## Containers for a Customer [/customers/{customerId}/containers]

### List All Containers [GET]

This endpoint uses the *internal* ID for the Customer.

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/customers/<customer id>/containers
```

+ Parameters
 + cursor: (string, optional)

+ Response 200 (application/json)

    + Body

            {
              "payload": [
                {
                  "id": "1234NDROPWASTE_00014",
                  "containerType": "roll off",
                  "contentType": "refuse",
                  "cubicYards": 20,
                  "description": "20-0009",
                  "externalId": "YRTRPS4HCB91",
                  "hasAccuratePosition": true,
                  "lastClassifiedCameraBlocked": false,
                  "lastGpsIsAccurate": true,
                  "lastImageTimestamp": "2019-07-26T22:19:07.799Z",
                  "lastImageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-04bcbcdeabba",
                  "level": 70,
                  "location": {
                    "id": "12341111-1111-1111-1111-11f12747b600",
                    "externalId": null,
                    "description": "Zellers",
                    "street": "473 Tehama Street, #B",
                    "city": "San Francisco",
                    "state": "CA",
                    "postalCode": "94103",
                    "zip": "94103"
                  },
                  "locationUpdatedAt": "2019-07-19T19:52:40.988Z",
                  "latitude": 30.312946,
                  "longitude": -97.986297,
                  "maybeLastEmptiedAt": "2019-06-18T20:10:17.000Z",
                  "pendingClassification": true,
                  "pickupSchedule": {
                    "currency": "usd",
                    "frequency": "weekly",
                    "friday": false,
                    "monday": true,
                    "price": "120.00",
                    "saturday": false,
                    "sunday": false,
                    "thursday": true,
                    "tuesday": false,
                    "wednesday": false
                  },
                  "positionAccuracy": 9.3,
                  "technicianAssigned": false,
                  "updatedAt": "2019-07-26T22:21:24.240Z"
                }
              ],
              "client": [ 
                "X-Compology-Version: 2019-07-25/1"
              ],
              "next": "https://containers-api.compology.com/v2/TEHAMA123/containers/?cursor=eyJkaXJlY3Rpb240YWIwNGZmIn0%3D"
            }

## Containers for a Customer by external ID [/customers/e/{externalCustomerId}/containers]

### List All Containers [GET]

This endpoint uses the *external* ID for the Customer.

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/customers/e/<external customer id>/containers
```

+ Parameters
 + cursor: (string, optional)

+ Response 200 (application/json)

    + Body

            {
              "payload": [
                {
                  "id": "1234NDROPWASTE_00014",
                  "containerType": "roll off",
                  "contentType": "refuse",
                  "cubicYards": 20,
                  "description": "20-0009",
                  "externalId": "YRTRPS4HCB91",
                  "hasAccuratePosition": true,
                  "lastClassifiedCameraBlocked": false,
                  "lastGpsIsAccurate": true,
                  "lastImageTimestamp": "2019-07-26T22:19:07.799Z",
                  "lastImageUrl": "https://images.compology.com/1/raw_device_data/12341111-1111-1111-1111-04bcbcdeabba",
                  "level": 70,
                  "location": {
                    "id": "12341111-1111-1111-1111-11f12747b600",
                    "externalId": null,
                    "description": "Zellers",
                    "street": "473 Tehama Street, #B",
                    "city": "San Francisco",
                    "state": "CA",
                    "postalCode": "94103",
                    "zip": "94103"
                  },
                  "locationUpdatedAt": "2019-07-19T19:52:40.988Z",
                  "latitude": 30.312946,
                  "longitude": -97.986297,
                  "maybeLastEmptiedAt": "2019-06-18T20:10:17.000Z",
                  "pendingClassification": true,
                  "pickupSchedule": {
                    "currency": "usd",
                    "frequency": "weekly",
                    "friday": false,
                    "monday": true,
                    "price": "120.00",
                    "saturday": false,
                    "sunday": false,
                    "thursday": true,
                    "tuesday": false,
                    "wednesday": false
                  },
                  "positionAccuracy": 9.3,
                  "technicianAssigned": false,
                  "updatedAt": "2019-07-26T22:21:24.240Z"
                }
              ],
              "client": [ 
                "X-Compology-Version: 2019-07-25/1"
              ]
            }


## Feed-style Device Posts [/device_posts]

### List All Device Posts [GET]

Feed-style endpoints provide a way to "sync" data between a client and
the Compology server.  By setting `updatedBefore` to the current time and
`updatedAfter` to some time in the past, and paging through the results,
a client can effectively get a copy of all the records in the Compology
system.  By repeating this process (setting the `updatedAfter` time to
equal the previous `updatedBefore` time), the two systems can be kept in
sync.

The query parameter `updatedAfter` is an inclusive bound -- eg, records
that were updated exactly at the time specified by `updatedAfter` will be
included in the response.

The query parameter updatedBefore is an exclusive bound -- eg, records
that were updated exactly at the time specified by `updatedBefore` will
be excluded from the response.

Neither `updatedAfter` nor `updatedBefore` may specify times in the future.

The value of `updatedAfter` may not be greater than the value of `updatedBefore`.

Any truncation of precision will be filled in with zeros, so eg,
“updatedAfter=2020-01-01” will show all of Jan 1st’s records because it
will be interpreted as “updatedAfter=2020-01-01:00:00:00.000”

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/device_posts?updatedAfter=2020-01-01&updatedBefore=2021-01-01
```

+ Parameters
 + updatedAfter: `2020-01-01T12:00` (string, required) - An ISO8601 date
 + updatedBefore: `2021-01-01T12:00` (string, required) - An ISO8601 date

+ Response 200 (application/json)

    + Body

            {
              "payload": [
                {
                  "id": "1234bd1b-c18a-4971-a24f-e2a4f8807a8e",
                  "organizationId": "EXCORP",
                  "containerId": "EXCORP_00016",
                  "occurredAt": "2020-09-01T00:57:01.997Z",
                  "updatedAt": "2020-09-01T01:01:12.356Z",
                  "level": 30,
                  "pendingLevelAnalysis": false,
                  "cameraBlocked": false,
                  "latitude": 37.77172,
                  "longitude": -122.407249,
                  "imageUrl": "https://images.compology.com/1/raw_device_data/1234bd1b-c18a-4971-a24f-e2a4f8807a8e",
                  "fillCycleId": "1234cd7a-15ea-4e9c-bb8d-cdada66b9a36",
                  "locationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                  "pendingLocationMatch": false,
                  "visibleContamination": {
                    "plastic bag": {
                      "count": 2
                    },
                    "bulky item": {
                      "count": 0
                    },
                    "tanglers": {
                      "count": 0
                    },
                    "e-waste": {
                      "count": 0
                    },
                    "uncollapsed cardboard box": {
                      "count": 0
                    },
                    "styrofoam": {
                      "count": 0
                    }
                  },
                  "pendingContaminationAnalysis": false,
                  "visibleContent": {
                    "plastic bag": {
                      "count": 2
                    },
                    "bulky item": {
                      "count": 0
                    },
                    "tanglers": {
                      "count": 0
                    },
                    "e-waste": {
                      "count": 0
                    },
                    "uncollapsed cardboard box": {
                      "count": 0
                    },
                    "styrofoam": {
                      "count": 0
                    }
                  },
                  "pendingContentAnalysis": false,
                  "wasEmptied": false,
                  "pendingWasEmptiedAnalysis": false
                },
                {
                  "id": "12349b17-db8c-4f92-966f-5c6ec033b33c",
                  "organizationId": "EXCORP",
                  "containerId": "EXCORP_00021",
                  "occurredAt": "2020-09-01T00:56:42.222Z",
                  "updatedAt": "2020-09-01T01:02:41.720Z",
                  "level": 10,
                  "pendingLevelAnalysis": false,
                  "cameraBlocked": false,
                  "latitude": null,
                  "longitude": null,
                  "imageUrl": "https://images.compology.com/1/raw_device_data/12349b17-db8c-4f92-966f-5c6ec033b33c",
                  "fillCycleId": "12344b93-e9b7-4758-bf98-943d05770a2e",
                  "locationId": null,
                  "pendingLocationMatch": true,
                  "visibleContamination": {
                    "bulky item": {
                      "count": 0
                    },
                    "e-waste": {
                      "count": 0
                    },
                    "uncollapsed cardboard box": {
                      "count": 0
                    }
                  },
                  "pendingContaminationAnalysis": false,
                  "visibleContent": {
                    "bulky item": {
                      "count": 0
                    },
                    "e-waste": {
                      "count": 0
                    },
                    "uncollapsed cardboard box": {
                      "count": 0
                    }
                  },
                  "pendingContentAnalysis": false,
                  "wasEmptied": false,
                  "pendingWasEmptiedAnalysis": false
                },
                {
                  "id": "12343199-ccdf-4d10-98fb-f2fde23771e9",
                  "organizationId": "EXCORP",
                  "containerId": "EXCORP_00026",
                  "occurredAt": "2020-09-11T08:58:30.688Z",
                  "updatedAt": "2020-09-11T20:16:10.286Z",
                  "level": null,
                  "pendingLevelAnalysis": false,
                  "cameraBlocked": true,
                  "latitude": null,
                  "longitude": null,
                  "imageUrl": "https://images.compology.com/1/raw_device_data/12343199-ccdf-4d10-98fb-f2fde23771e9",
                  "fillCycleId": "12346d35-9f93-4050-a497-1e32830adb01",
                  "locationId": null,
                  "pendingLocationMatch": true,
                  "visibleContamination": {
                    "bulky item": {},
                    "e-waste": {},
                    "uncollapsed cardboard box": {}
                  },
                  "pendingContaminationAnalysis": false,
                  "visibleContent": {
                    "bulky item": {},
                    "e-waste": {},
                    "uncollapsed cardboard box": {}
                  },
                  "pendingContentAnalysis": false,
                  "wasEmptied": false,
                  "pendingWasEmptiedAnalysis": false
                }
              ],
              "client": [
                "X-Compology-Version: 2019-07-25/1"
              ],
              "next": "https://containers-api.compology.com/v2/device_posts?cursor=eyJpZCI6ImYxNjE0N2MyLTRlMmItNGM0ODdiMyIsInVwZGF0ZWRBZnRlciI6IjIwMjAtMDktMDMgMDE6MDM6NDEuNDI1MDIyKzAwIiwidXBkYXRlZEJlZm9y00000000MjEtMDEtMDEifQ%3D%3D"
            }


## Feed-style Fill Cycles [/fill_cycles]

### List All Fill Cycles [GET]

See the above `/device_posts` documentation for a description of
"feed-style endpoints".  This `/fill_cycles` endpoint follows the same
pattern and has the same constraints on `updatedAfter` and `updatedBefore`.

#### example
```bash
export BASE=https://containers-api.compology.com/v2
export AUTH="Authorization: Bearer <your auth token>"
curl -H 'Accept: application/json' -H "$AUTH" ${BASE}/fill_cycles?updatedAfter=2020-01-01&updatedBefore=2021-01-01
```

+ Parameters
 + updatedAfter: `2020-01-01T12:00` (string, required) - An ISO8601 date
 + updatedBefore: `2020-01-01T12:00` (string, required) - An ISO8601 date

+ Response 200 (application/json)

    + Body

            {
              "payload": [
                {
                  "id": "1234b42d-12e2-40ab-a0d5-107442eac33f",
                  "containerId": "EXCORP_00023",
                  "startedAt": "2020-09-10T14:30:03.968Z",
                  "endedAt": "2020-09-11T16:23:55.309Z",
                  "updatedAt": "2020-09-11T20:15:19.362Z",
                  "recentDevicePostsInCycle": [
                    {
                      "id": "123420bd-b412-4458-ba5f-04ddfce4840b",
                      "imageTimestamp": "2020-09-11T13:03:37.150Z",
                      "updatedAt": "2020-09-11T13:05:22.816Z",
                      "level": null,
                      "cameraBlocked": true,
                      "latitude": 32.982143,
                      "longitude": -96.706619,
                      "latLonRadius": 12,
                      "locationId": "12341ad5-e5ef-46ed-8d83-596bb7e668ac",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/123420bd-b412-4458-ba5f-04ddfce4840b"
                    },
                    {
                      "id": "1234c543-f398-4968-80fa-9babff5ff4b6",
                      "imageTimestamp": "2020-09-11T08:57:00.556Z",
                      "updatedAt": "2020-09-11T08:59:07.380Z",
                      "level": 85,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234c543-f398-4968-80fa-9babff5ff4b6"
                    },
                    {
                      "id": "1234c18e-edcf-4cfa-8347-3fce0fe47845",
                      "imageTimestamp": "2020-09-11T01:17:37.470Z",
                      "updatedAt": "2020-09-11T01:20:05.957Z",
                      "level": 75,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234c18e-edcf-4cfa-8347-3fce0fe47845"
                    },
                    {
                      "id": "1234d720-c5d6-4d8b-8738-3883737c3a36",
                      "imageTimestamp": "2020-09-11T01:01:29.408Z",
                      "updatedAt": "2020-09-11T01:03:35.561Z",
                      "level": 15,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234d720-c5d6-4d8b-8738-3883737c3a36"
                    },
                    {
                      "id": "1234ad77-1d93-4929-a8a0-6e7dd32af82f",
                      "imageTimestamp": "2020-09-10T17:00:29.021Z",
                      "updatedAt": "2020-09-10T17:02:35.190Z",
                      "level": 5,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234ad77-1d93-4929-a8a0-6e7dd32af82f"
                    }
                  ],
                  "level": 85,
                  "cameraBlocked": true,
                  "pendingLevelAnalysis": false,
                  "cumulativeContamination": {
                    "bulky item": {
                      "count": 0,
                      "reason": []
                    },
                    "e-waste": {
                      "count": 0,
                      "reason": []
                    },
                    "uncollapsed cardboard box": {
                      "count": 1,
                      "reason": [
                        {
                          "count": 1,
                          "devicePostId": "1234d720-c5d6-4d8b-8738-3883737c3a36"
                        }
                      ]
                    }
                  },
                  "cScore": 0.5882352941176471,
                  "pendingContaminationAnalysis": true,
                  "cyclePickupLocationId": "12341ad5-e5ef-46ed-8d83-596bb7e668ac",
                  "cycleCustomerId": "1234cec5-21ac-468e-8d33-4c854c099059"
                },
                {
                  "id": "1234cd7a-15ea-4e9c-bb8d-cdada66b9a36",
                  "containerId": "EXCORP_00016",
                  "startedAt": "2020-08-31T00:58:53.056Z",
                  "endedAt": "2020-09-11T14:32:23.603Z",
                  "updatedAt": "2020-09-11T20:15:59.680Z",
                  "recentDevicePostsInCycle": [
                    {
                      "id": "123446d3-dae3-4c75-b7b4-a2a2f5ffeb8f",
                      "imageTimestamp": "2020-09-11T12:32:20.729Z",
                      "updatedAt": "2020-09-11T12:33:04.217Z",
                      "level": null,
                      "cameraBlocked": true,
                      "latitude": 37.772018,
                      "longitude": -122.40715,
                      "latLonRadius": 30,
                      "locationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/123446d3-dae3-4c75-b7b4-a2a2f5ffeb8f"
                    },
                    {
                      "id": "12344790-8f3c-4ea6-b63c-66eb67732dfb",
                      "imageTimestamp": "2020-09-11T09:00:08.712Z",
                      "updatedAt": "2020-09-11T09:02:34.138Z",
                      "level": 88,
                      "cameraBlocked": false,
                      "latitude": 37.771915,
                      "longitude": -122.407485,
                      "latLonRadius": 29,
                      "locationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/12344790-8f3c-4ea6-b63c-66eb67732dfb"
                    },
                    {
                      "id": "1234c010-81ec-4d71-9012-8ff39ab03756",
                      "imageTimestamp": "2020-09-11T06:08:18.579Z",
                      "updatedAt": "2020-09-11T06:09:20.825Z",
                      "level": 98,
                      "cameraBlocked": false,
                      "latitude": 37.772323,
                      "longitude": -122.407447,
                      "latLonRadius": 29,
                      "locationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234c010-81ec-4d71-9012-8ff39ab03756"
                    },
                    {
                      "id": "123460eb-e2cf-4f3d-87a0-e91cde291644",
                      "imageTimestamp": "2020-09-11T00:59:12.235Z",
                      "updatedAt": "2020-09-11T01:02:26.235Z",
                      "level": 90,
                      "cameraBlocked": false,
                      "latitude": 37.771793,
                      "longitude": -122.407646,
                      "latLonRadius": 33,
                      "locationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/123460eb-e2cf-4f3d-87a0-e91cde291644"
                    },
                    {
                      "id": "1234128c-19bb-4298-b741-7075158d5885",
                      "imageTimestamp": "2020-09-10T16:58:23.363Z",
                      "updatedAt": "2020-09-10T17:00:14.873Z",
                      "level": 80,
                      "cameraBlocked": false,
                      "latitude": 37.771801,
                      "longitude": -122.406913,
                      "latLonRadius": 24,
                      "locationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234128c-19bb-4298-b741-7075158d5885"
                    }
                  ],
                  "level": 88,
                  "cameraBlocked": true,
                  "pendingLevelAnalysis": false,
                  "cumulativeContamination": {
                    "plastic bag": {
                      "count": 3,
                      "reason": [
                        {
                          "count": 3,
                          "devicePostId": "12348eb9-27b6-42ca-9695-9ec33b658ad6"
                        }
                      ]
                    },
                    "bulky item": {
                      "count": 0,
                      "reason": []
                    },
                    "tanglers": {
                      "count": 0,
                      "reason": []
                    },
                    "styrofoam": {
                      "count": 0,
                      "reason": []
                    },
                    "uncollapsed cardboard box": {
                      "count": 1,
                      "reason": [
                        {
                          "count": 1,
                          "devicePostId": "12344790-8f3c-4ea6-b63c-66eb67732dfb"
                        }
                      ]
                    },
                    "e-waste": {
                      "count": 0,
                      "reason": []
                    }
                  },
                  "cScore": 4.545454545454546,
                  "pendingContaminationAnalysis": true,
                  "cyclePickupLocationId": "123428d2-85f3-456c-af87-dbf6f4857f86",
                  "cycleCustomerId": "1234a05c-a7a5-4d40-ae63-a1720a3604d4"
                },
                {
                  "id": "12349e68-3599-4112-a823-0f217a33afb0",
                  "containerId": "EXCORP_00024",
                  "startedAt": "2020-09-10T14:23:14.464Z",
                  "endedAt": "2020-09-11T16:31:06.462Z",
                  "updatedAt": "2020-09-11T20:16:06.756Z",
                  "recentDevicePostsInCycle": [
                    {
                      "id": "12344880-8605-4a21-9a17-52527cb3f1a6",
                      "imageTimestamp": "2020-09-11T16:20:15.501Z",
                      "updatedAt": "2020-09-11T16:21:53.979Z",
                      "level": null,
                      "cameraBlocked": true,
                      "latitude": 32.982471,
                      "longitude": -96.706718,
                      "latLonRadius": 27,
                      "locationId": "12341ad5-e5ef-46ed-8d83-596bb7e668ac",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/12344880-8605-4a21-9a17-52527cb3f1a6"
                    },
                    {
                      "id": "12348894-94de-4f34-b540-039569c81db2",
                      "imageTimestamp": "2020-09-11T12:55:11.344Z",
                      "updatedAt": "2020-09-11T12:55:56.816Z",
                      "level": null,
                      "cameraBlocked": true,
                      "latitude": 32.982158,
                      "longitude": -96.706543,
                      "latLonRadius": 27,
                      "locationId": "12341ad5-e5ef-46ed-8d83-596bb7e668ac",
                      "imageUrl": "https://images.compology.com/1/raw_device_data/12348894-94de-4f34-b540-039569c81db2"
                    },
                    {
                      "id": "1234232e-956d-4056-8505-d36c434dfa21",
                      "imageTimestamp": "2020-09-11T12:35:12.240Z",
                      "updatedAt": "2020-09-11T12:37:26.819Z",
                      "level": 20,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/1234232e-956d-4056-8505-d36c434dfa21"
                    },
                    {
                      "id": "12341201-0b16-4d5c-9057-ca5ede1b0b9b",
                      "imageTimestamp": "2020-09-11T08:59:50.943Z",
                      "updatedAt": "2020-09-11T09:01:56.194Z",
                      "level": 5,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/12341201-0b16-4d5c-9057-ca5ede1b0b9b"
                    },
                    {
                      "id": "123485ee-5492-4167-ab32-522a9b45eb46",
                      "imageTimestamp": "2020-09-11T01:00:10.714Z",
                      "updatedAt": "2020-09-11T01:02:15.753Z",
                      "level": 10,
                      "cameraBlocked": false,
                      "latitude": null,
                      "longitude": null,
                      "latLonRadius": 0,
                      "locationId": null,
                      "imageUrl": "https://images.compology.com/1/raw_device_data/123485ee-5492-4167-ab32-522a9b45eb46"
                    }
                  ],
                  "level": 20,
                  "cameraBlocked": true,
                  "pendingLevelAnalysis": false,
                  "cumulativeContamination": {
                    "uncollapsed cardboard box": {
                      "count": 0,
                      "reason": []
                    },
                    "bulky item": {
                      "count": 0,
                      "reason": []
                    },
                    "e-waste": {
                      "count": 0,
                      "reason": []
                    }
                  },
                  "cScore": 0,
                  "pendingContaminationAnalysis": true,
                  "cyclePickupLocationId": "12341ad5-e5ef-46ed-8d83-596bb7e668ac",
                  "cycleCustomerId": "1234cec5-21ac-468e-8d33-4c854c099059"
                }
              ],
              "client": [
                "X-Compology-Version: 2019-07-25/1"
              ]
              "next": "https://containers-api.compology.com/v2/fill_cycles?cursor=eyJoYXVsSWQiOiJwZDk5OWEiLCJ1cGRhdGVkQWZ0ZXIiOiIyMDIwLT00000000IwOjE1OjAxLjU1MTA1MiswMCIsInVwZGF0ZWRCZWZvcmUiOiIyMDIxLTAxLTAxIn0%3D"
            }


